spring.application.name=gym-workload
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/trainer_mongodb?replicaSet=rs0

# Actuator
management.endpoints.web.exposure.include=*

# ActiveMQ Configuration
spring.activemq.broker-url=tcp://localhost:61616
spring.jms.listener.concurrency=2
spring.jms.listener.max-concurrency=5
