spring.application.name=gym-workload
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database (H2)
spring.datasource.url=jdbc:h2:mem:workloaddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Database (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/trainer_mongodb

# Actuator
management.endpoints.web.exposure.include=*

# ActiveMQ Configuration
spring.activemq.broker-url=tcp://localhost:61616
spring.jms.listener.concurrency=2
spring.jms.listener.max-concurrency=5
